<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>0.0.1</Version>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>run_llm</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BoxOfYellow.ConsoleMarkdownRenderer.Spectre" Version="0.12.5" />
    <PackageReference Include="LLamaSharp" Version="0.27.0" />
    <PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.27.0" />
    <PackageReference Include="LLamaSharp.semantic-kernel" Version="0.27.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.80.1" />
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="llm.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectrory>PreserveNewest</CopyToPublishDirectrory>
    </Content>
  </ItemGroup>
</Project>
